import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
// import AppFont from "@/fonts/app-font";

import { Lato } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { SocketProvider } from "@/providers/socket";
import UserNameModal from "@/components/user-name/user-name-modal";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        {/* <AppFont /> */}
        <SocketProvider>
          <UserNameModal />
          <Header />
          {children}
          <Toaster />
        </SocketProvider>
      </body>
    </html>
  );
}
